env:
  browser: true
  es6: true
  amd: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
  sourceType: 'module'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - single
  no-console:
    - off
  no-unused-vars:
    - warn
